name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Access local server
      run: |
        curl -X GET 0.tcp.sa.ngrok.io:15346/usuario
